In [2]:
import numpy as np
import pandas as pd

In [4]:
series_1 = pd.Series([1, 2, 3, 4, 5, np.nan, 5, 7])
series_1

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
6    5.0
7    7.0
dtype: float64

In [6]:
dates = pd.date_range("2013-01-01", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [9]:
pd.Series(1, index=list(range(4)), dtype="float32")

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32

In [11]:
np.array([3] * 4, dtype="int32")

array([3, 3, 3, 3], dtype=int32)

In [37]:
np.random.randint(1, 10, size = 4)

array([9, 5, 6, 1])

In [38]:
data_dict = {
    "A" : 1.0,
    "B" : pd.Timestamp("2013-01-02"),
    "C" : pd.Series(1, index=list(range(4)), dtype="float32"),
    "D" : np.random.randint(1, 10, size = 4),
    "E" : pd.Categorical(["test", "train", "test", "train"]),
    "F" : "foo"
}
df2 = pd.DataFrame(data_dict)
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  4   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  7   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [39]:
pd.Series(1, dtype="float32")

0    1.0
dtype: float32

In [40]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int64
E         category
F           object
dtype: object

In [41]:
df2.head()

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  4   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  7   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [42]:
df2.tail()

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  4   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  7   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [43]:
df2.index

Index([0, 1, 2, 3], dtype='int64')

In [44]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [45]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 4, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 7, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [46]:
df2.describe()

A                    B    C         D
count  4.0                    4  4.0  4.000000
mean   1.0  2013-01-02 00:00:00  1.0  4.250000
min    1.0  2013-01-02 00:00:00  1.0  3.000000
25%    1.0  2013-01-02 00:00:00  1.0  3.000000
50%    1.0  2013-01-02 00:00:00  1.0  3.500000
75%    1.0  2013-01-02 00:00:00  1.0  4.750000
max    1.0  2013-01-02 00:00:00  1.0  7.000000
std    0.0                  NaN  0.0  1.892969

In [47]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  4   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  7   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [48]:
df2.T

0                    1                    2  \
A                  1.0                  1.0                  1.0   
B  2013-01-02 00:00:00  2013-01-02 00:00:00  2013-01-02 00:00:00   
C                  1.0                  1.0                  1.0   
D                    4                    3                    7   
E                 test                train                 test   
F                  foo                  foo                  foo   

                     3  
A                  1.0  
B  2013-01-02 00:00:00  
C                  1.0  
D                    3  
E                train  
F                  foo

In [49]:
df2.head()

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  4   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  7   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [50]:
a = df2.sort_index(axis=1, ascending=True)
a

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  4   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  7   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [53]:
df2.sort_values(by="D", ascending = False)

A          B    C  D      E    F
2  1.0 2013-01-02  1.0  7   test  foo
0  1.0 2013-01-02  1.0  4   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [54]:
df2.head()

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  4   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  7   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

## Selection and Indexing and Slicing

In [55]:
df2["A"]

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [58]:
df2[1:3]

A          B    C  D      E    F
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  7   test  foo

In [60]:
df2.loc[:, ["B", "D"]]

B  D
0 2013-01-02  4
1 2013-01-02  3
2 2013-01-02  7
3 2013-01-02  3

In [61]:
df2.iloc[0:2, 0:2]

A          B
0  1.0 2013-01-02
1  1.0 2013-01-02

## Boolean Indexing

In [63]:
df2[df2["D"] > 3]

A          B    C  D     E    F
0  1.0 2013-01-02  1.0  4  test  foo
2  1.0 2013-01-02  1.0  7  test  foo

## Pivot Table

In [3]:
df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
     }
)

In [6]:
df

A  B    C         D         E
0     one  A  foo  1.013946 -0.379204
1     one  B  foo  0.014950 -0.617906
2     two  C  foo  1.096121  0.111350
3   three  A  bar  0.125811  0.096834
4     one  B  bar  0.479675 -1.012213
5     one  C  bar -1.983336 -0.292120
6     two  A  foo -0.613398 -0.381250
7   three  B  foo -0.505857 -0.786271
8     one  C  foo  0.317663  1.801405
9     one  A  bar  0.666416 -0.590423
10    two  B  bar -1.124216 -0.662441
11  three  C  bar  0.554555 -1.355853

In [5]:
pd.pivot_table(df, values="D", index=["A", "B"], columns=["C"])

C             bar       foo
A     B                    
one   A  0.666416  1.013946
      B  0.479675  0.014950
      C -1.983336  0.317663
three A  0.125811       NaN
      B       NaN -0.505857
      C  0.554555       NaN
two   A       NaN -0.613398
      B -1.124216       NaN
      C       NaN  1.096121

## Time Series

In [10]:
rng = pd.date_range("1/1/2012", periods=100, freq="s")
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [11]:
ts

2012-01-01 00:00:00     52
2012-01-01 00:00:01    222
2012-01-01 00:00:02      0
2012-01-01 00:00:03    304
2012-01-01 00:00:04    206
                      ... 
2012-01-01 00:01:35     39
2012-01-01 00:01:36     38
2012-01-01 00:01:37    406
2012-01-01 00:01:38    311
2012-01-01 00:01:39    401
Freq: s, Length: 100, dtype: int64

## Categorical

In [24]:
df = pd.DataFrame(
    {"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "c"]}
)
df

id raw_grade
0   1         a
1   2         b
2   3         b
3   4         a
4   5         a
5   6         c

In [25]:
df["grade"] = df["raw_grade"].astype("category")
df["grade"]

0    a
1    b
2    b
3    a
4    a
5    c
Name: grade, dtype: category
Categories (3, object): ['a', 'b', 'c']

In [26]:
df

id raw_grade grade
0   1         a     a
1   2         b     b
2   3         b     b
3   4         a     a
4   5         a     a
5   6         c     c

In [27]:
new_categories = ["very good", "good", "very bad"]
df["grade"] = df["grade"].cat.rename_categories(new_categories)

In [28]:
df

id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         c   very bad

In [29]:
df["grade"] = df["grade"].cat.set_categories(
    ["very bad", "bad", "medium", "good", "very good"]
)

df["grade"]

0    very good
1         good
2         good
3    very good
4    very good
5     very bad
Name: grade, dtype: category
Categories (5, object): ['very bad', 'bad', 'medium', 'good', 'very good']